# Generated by Django 5.1.2 on 2024-11-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_auth', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Called',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization', models.CharField(max_length=250)),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Atendido', 'Atendido'), ('Não atendido', 'Não atendido')], default='Aberto', max_length=15)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=200)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_problem', to='problem.problem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='called_user', to='my_auth.usermobile')),
            ],
        ),
    ]
