# Generated by Django 5.1.2 on 2024-11-12 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0002_imagescalled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagescalled',
            name='called',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_called', to='called.called'),
        ),
    ]
