# Generated by Django 5.1.2 on 2024-11-12 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0003_alter_imagescalled_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='called',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
