# Generated by Django 5.1.2 on 2024-11-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0004_called_date'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='called',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_called', to='city.city'),
        ),
    ]
