# Generated by Django 5.1.2 on 2024-12-11 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0006_called_user_mobile_alter_called_user'),
        ('service_order', '0007_remove_serviceorder_calleds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='called',
            name='first_called',
            field=models.BooleanField(default=True, verbose_name='Primeiro?'),
        ),
        migrations.AddField(
            model_name='called',
            name='service_order',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='calleds', to='service_order.serviceorder', verbose_name='Chamados'),
            preserve_default=False,
        ),
    ]
