# Generated by Django 5.1.2 on 2024-12-11 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0007_called_first_called_called_service_order'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='called',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_user', to='my_auth.user'),
        ),
        migrations.AlterField(
            model_name='called',
            name='user_mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_user_mobile', to='my_auth.usermobile'),
        ),
    ]
