# Generated by Django 5.1.2 on 2024-12-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0008_alter_called_user_alter_called_user_mobile'),
        ('service_order', '0007_remove_serviceorder_calleds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='called',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calleds', to='service_order.serviceorder', verbose_name='Ordem de serviço'),
        ),
    ]
