# Generated by Django 5.1.2 on 2024-12-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0009_alter_called_service_order'),
        ('city', '0004_alter_city_latitude_alter_city_longitude'),
        ('service_order', '0007_remove_serviceorder_calleds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='called',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='city.city'),
        ),
        migrations.AlterField(
            model_name='called',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calleds', to='service_order.serviceorder', verbose_name='Ordem de serviço'),
        ),
    ]
