# Generated by Django 5.1.2 on 2024-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0010_alter_called_city_alter_called_service_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='called',
            name='additional_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
