# Generated by Django 5.1.2 on 2024-12-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0012_alter_called_first_called'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='called',
            options={'ordering': ['-first_called', '-service_order']},
        ),
    ]
