# Generated by Django 5.1.2 on 2024-11-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagesCalled',
            new_name='ImagesDaily',
        ),
    ]
