# Generated by Django 5.1.2 on 2024-11-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TownHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('infos', models.TextField(blank=True, null=True)),
                ('generates_open_os', models.BooleanField(default=False)),
            ],
        ),
    ]
