# Generated by Django 5.1.2 on 2024-11-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('town_hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='townhall',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='town_hall_city', to='city.city', verbose_name='Município'),
            preserve_default=False,
        ),
    ]
