# Generated by Django 5.1.2 on 2024-12-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town_hall', '0002_townhall_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='townhall',
            name='city',
        ),
    ]
