# Generated by Django 5.1.2 on 2024-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('called', '0004_called_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Requisitada', 'Requisitada'), ('Rejeitada', 'Rejeitada'), ('Aberta', 'Aberta'), ('Concluída', 'Concluída')], default='Requisitada', max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('calleds', models.ManyToManyField(to='called.called', verbose_name='Chamados')),
            ],
        ),
    ]
