# Generated by Django 5.1.2 on 2024-11-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0004_called_date'),
        ('service_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='calleds',
            field=models.ManyToManyField(related_name='called_so', to='called.called', verbose_name='Chamados'),
        ),
    ]
