# Generated by Django 5.1.2 on 2024-11-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0003_serviceorder_first_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
