# Generated by Django 5.1.2 on 2024-11-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0004_serviceorder_open_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='status',
            new_name='type',
        ),
    ]
