# Generated by Django 5.1.2 on 2024-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0005_rename_status_serviceorder_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='type',
            new_name='status',
        ),
    ]
