# Generated by Django 5.1.2 on 2024-12-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0006_rename_type_serviceorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='calleds',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='first_called',
        ),
    ]
