# Generated by Django 5.1.2 on 2024-12-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem',
            new_name='description',
        ),
    ]
