# Generated by Django 5.1.2 on 2024-11-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Neighborhood_city', to='city.city', verbose_name='Município')),
            ],
        ),
    ]
